### ISSUE TITLE
Tracking issue for graphql 3.0

### ISSUE THREAD

**Issue by ganwell** [projectcaluma/caluma#814]
- [x] !! Sync everything: there is #1413, which should be force-pushed to graphene_django_v3 #1438
- [x] Make pytests order-independent in master
- [x] Lower coverage (done in #1413)
- [x] Enable xfaillist #1413
- [x] Fix all pytests in graphene_django_v3 branch (pytest-xfaillist)
- [x] Upstream bugs (if found)
- [x] Disable xfaillist
- [x] Increase coverage
- [x] Fix coverage
- [x] merge master to graphene_django_v3 contantly 
- [x] Merge to master

**Comment by sbor23** [comment]
@ganwell would you mind updating the checklist?

**Comment by ganwell** [comment]
@sbor23 Ok?
