### ISSUE TITLE
[workflow] Caluma "events" (signals)

### ISSUE THREAD

**Issue by open-dynaMIX** [projectcaluma/caluma#970]
## Rationale

We want Caluma to emit signals at certain stages of workflows.

Right now we solve this in various projects with the (mis-)use of the `validations` extension. This has various shortcomings:

 - It handles work that can't be considered "validation"
 - We want to trigger actions after making sure the validation will be successful. Hence duplicating the actual validation. This can lead to dangerous situations: What if our duplicated validation let's something slip through the actual validation prohibits at a later point?
 - It is tied to requests and exclusively takes place in the context of them.
 - It clutters the actual validation extension --> actual validation vs. tasks we want to run at the successful end of a mutation

Signals will provide us with a simple and transparent way to react on certain events.

In order for users of the Caluma service to make use of those signals, we propose an additional extension `events.py`.

## Signal receivers are blocking

For this kind of "side-effects" it is desirable, that receivers are non-blocking. This is not possible with plain signals. In order to provide us with a base that will allow us to extend Caluma events in a way that enables non-blocking receivers of events, we propose to build a simple wrapper (or just an alias) around the `django.dispatch.receiver` decorator called `@on`.

So in a first step, we will implement Caluma "events" in a blocking manner, using the `@on` decorator. At a later point, we will be able to delegate the execution of the receiver function to celery or another task queue. As we don't see a valid usecase for blocking receivers vs. non-blocking, this is considered an implementation detail that does not affect the public API.

## Bigger context

This proposed change has to be viewed in the context of the higher goal to make it as easy as possible for third-party applications to react on events in Caluma. Having this signals infrastructure in place will provide us with a good starting point to further pursue this goal.

Some related discussion can be found in #468.

## Example

Caluma emits an event when a `WorkItem` is completed. We want to send a notification when this happens. This could be implemented as follows in the `events` extension:

``` python
from caluma_core.events import on
from caluma_workflow.events import complete_work_item


@on(complete_work_item)
def send_mail_on_complete_work_item(sender, work_item, **kwargs):
    if work_item.task.slug == "slug-we-are-interested-in":
        # send notification
        pass
```

## TODOs

 - [ ] Implement a sub-set of the needed signals we anticipate
 - [ ] Implement a wrapper around (or an alias for)  `django.dispatch.receiver` called `@on`
 - [ ] Implement an additional extension `events`
 - [ ] Document the events and their usage

**Comment by czosel** [comment]
Excellent write-up! 👏
I agree to all the points you made, and have just one feedback: I’m not sure if we should really call the extension „signal-handlers“. To answer what it should be called it would be great to see an example how the API would look like. Only if signals are something we consider inherent to the use-case I’d call it like that. But if it’s just a bunch of methods one can implement as reactions to things that happen inside Caluma, we could consider calling it „side-effects“, „event-handlers“, ... you name it - which would allow changing the implementation to something other than signals in the future while keeping the public API.

The advantage of calling it signal-handlers is that the direct consumption of the signals in our „Caluma as django app“ scenario becomes more natural.

I guess the more broad question is: Does the name „signal“ make sense for people who don’t know django (nor django signals) as well?

**Comment by open-dynaMIX** [comment]
@czosel I've updated the description with an example usage. For now I've called the new extension `events`.

**Comment by czosel** [comment]
Awesome, thanks for the update! I like the name `events`, because it's understandable and doesn't "leak" implementation details. In the current example, we still have some references to signals though:
```py
from django.dispatch import receiver
from caluma_workflow.signals import complete_work_item_signal
```

I'm not sure if mixing "events" and "signals" is a good idea. Some alternatives:

- embrace the fact that we're using django signals, call the extension `signal-handlers` 
- hide everything that looks like signals, e.g.

```py
from caluma_workflow.events import on, complete_work_item

@on(complete_work_item)
def send_mail_on_complete_work_item(sender, work_item, **kwargs):
```

This would give use the chance to swap out the implementation from signals to something else without breaking changes in the future.

cc @winged @sbor23 @kaldras @anehx @sliverc

**Comment by open-dynaMIX** [comment]
@czosel I agree. I've updated the issue description to take this into account.

**Comment by sbor23** [comment]
Good job bringing this to "paper"! :100: 
I like the proposal, sounds like there's a good level of abstraction from the implementation with a well-defined API.

**Comment by winged** [comment]
Sorry I'm a bit late to the party! I like the idea and your write-up!

Just one thing: I don't agree on the point that we should wrap Django's infrastructure for this. When Django comes along with full async support, they'll need to do an explicitly async version anyway. So they'll do exactly what we're planning to do.

Also I think we don't need to hide Django as an implementation detail, as we're way too tightly coupled into it anyway. Let's just use Django's `@receiver` decorator and define our own events, as the Django documentation suggests.

**Comment by czosel** [comment]
Hmm, how about the case where we need async support before django supports it?

**Comment by winged** [comment]
> Hmm, how about the case where we need async support before django supports it?

Then we're in rather big trouble, as currently [Django will block calls](https://docs.djangoproject.com/en/3.0/topics/async/) (especially the ORM) when done when an event loop is active.

I've had a call with @open-dynaMIX about this - we need "background" processing first, before we need actual async, so we just need to be careful about the wording here.
